//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audatex.FraudCheckServiceReferences {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviceinterface_v1.b2b.audatex.com", ConfigurationName="FraudCheckServiceReferences.ClaimsHistoryServicePort")]
    public interface ClaimsHistoryServicePort {
        
        // CODEGEN: Generating message contract since the operation ping is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Audatex.FraudCheckServiceReferences.pingResponse ping(Audatex.FraudCheckServiceReferences.pingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Audatex.FraudCheckServiceReferences.pingResponse> pingAsync(Audatex.FraudCheckServiceReferences.pingRequest request);
        
        // CODEGEN: Generating message contract since the operation findExternal is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Audatex.FraudCheckServiceReferences.findExternalResponse findExternal(Audatex.FraudCheckServiceReferences.findExternalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Audatex.FraudCheckServiceReferences.findExternalResponse> findExternalAsync(Audatex.FraudCheckServiceReferences.findExternalRequest request);
        
        // CODEGEN: Generating message contract since the operation findInternal is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Audatex.FraudCheckServiceReferences.findInternalResponse findInternal(Audatex.FraudCheckServiceReferences.findInternalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Audatex.FraudCheckServiceReferences.findInternalResponse> findInternalAsync(Audatex.FraudCheckServiceReferences.findInternalRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceinterface_v1.b2b.audatex.com")]
    public partial class B2BRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private B2BParameter[] parameterField;
        
        private object payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter", Order=0)]
        public B2BParameter[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
                this.RaisePropertyChanged("parameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
                this.RaisePropertyChanged("payload");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceinterface_v1.b2b.audatex.com")]
    public partial class B2BParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        private bool xsltParameterField;
        
        private bool xsltParameterFieldSpecified;
        
        private string contextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool xsltParameter {
            get {
                return this.xsltParameterField;
            }
            set {
                this.xsltParameterField = value;
                this.RaisePropertyChanged("xsltParameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xsltParameterSpecified {
            get {
                return this.xsltParameterFieldSpecified;
            }
            set {
                this.xsltParameterFieldSpecified = value;
                this.RaisePropertyChanged("xsltParameterSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceinterface_v1.b2b.audatex.com")]
    public partial class B2BMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageCodeField;
        
        private int severityField;
        
        private string textField;
        
        private string localizedTextField;
        
        private string[] additionalInfoField;
        
        private string caseIdField;
        
        private string taskIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string messageCode {
            get {
                return this.messageCodeField;
            }
            set {
                this.messageCodeField = value;
                this.RaisePropertyChanged("messageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string localizedText {
            get {
                return this.localizedTextField;
            }
            set {
                this.localizedTextField = value;
                this.RaisePropertyChanged("localizedText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalInfo", Order=4)]
        public string[] additionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
                this.RaisePropertyChanged("additionalInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string caseId {
            get {
                return this.caseIdField;
            }
            set {
                this.caseIdField = value;
                this.RaisePropertyChanged("caseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
                this.RaisePropertyChanged("taskId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviceinterface_v1.b2b.audatex.com")]
    public partial class B2BResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnCodeField;
        
        private string loginIdField;
        
        private string hostNameField;
        
        private System.DateTime timestampField;
        
        private B2BMessage[] messageField;
        
        private object payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string loginId {
            get {
                return this.loginIdField;
            }
            set {
                this.loginIdField = value;
                this.RaisePropertyChanged("loginId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string hostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
                this.RaisePropertyChanged("hostName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message", Order=4)]
        public B2BMessage[] message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public object payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
                this.RaisePropertyChanged("payload");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pingRequest", Namespace="http://serviceinterface_v1.b2b.audatex.com", Order=0)]
        public Audatex.FraudCheckServiceReferences.B2BRequest pingRequest1;
        
        public pingRequest() {
        }
        
        public pingRequest(Audatex.FraudCheckServiceReferences.B2BRequest pingRequest1) {
            this.pingRequest1 = pingRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pingResponse", Namespace="http://serviceinterface_v1.b2b.audatex.com", Order=0)]
        public Audatex.FraudCheckServiceReferences.B2BResponse pingResponse1;
        
        public pingResponse() {
        }
        
        public pingResponse(Audatex.FraudCheckServiceReferences.B2BResponse pingResponse1) {
            this.pingResponse1 = pingResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findExternalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findExternalRequest", Namespace="http://serviceinterface_v1.b2b.audatex.com", Order=0)]
        public Audatex.FraudCheckServiceReferences.B2BRequest findExternalRequest1;
        
        public findExternalRequest() {
        }
        
        public findExternalRequest(Audatex.FraudCheckServiceReferences.B2BRequest findExternalRequest1) {
            this.findExternalRequest1 = findExternalRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findExternalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findExternalResponse", Namespace="http://serviceinterface_v1.b2b.audatex.com", Order=0)]
        public Audatex.FraudCheckServiceReferences.B2BResponse findExternalResponse1;
        
        public findExternalResponse() {
        }
        
        public findExternalResponse(Audatex.FraudCheckServiceReferences.B2BResponse findExternalResponse1) {
            this.findExternalResponse1 = findExternalResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findInternalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findInternalRequest", Namespace="http://serviceinterface_v1.b2b.audatex.com", Order=0)]
        public Audatex.FraudCheckServiceReferences.B2BRequest findInternalRequest1;
        
        public findInternalRequest() {
        }
        
        public findInternalRequest(Audatex.FraudCheckServiceReferences.B2BRequest findInternalRequest1) {
            this.findInternalRequest1 = findInternalRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findInternalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findInternalResponse", Namespace="http://serviceinterface_v1.b2b.audatex.com", Order=0)]
        public Audatex.FraudCheckServiceReferences.B2BResponse findInternalResponse1;
        
        public findInternalResponse() {
        }
        
        public findInternalResponse(Audatex.FraudCheckServiceReferences.B2BResponse findInternalResponse1) {
            this.findInternalResponse1 = findInternalResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClaimsHistoryServicePortChannel : Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClaimsHistoryServicePortClient : System.ServiceModel.ClientBase<Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort>, Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort {
        
        public ClaimsHistoryServicePortClient() {
        }
        
        public ClaimsHistoryServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClaimsHistoryServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaimsHistoryServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaimsHistoryServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Audatex.FraudCheckServiceReferences.pingResponse Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort.ping(Audatex.FraudCheckServiceReferences.pingRequest request) {
            return base.Channel.ping(request);
        }
        
        public Audatex.FraudCheckServiceReferences.B2BResponse ping(Audatex.FraudCheckServiceReferences.B2BRequest pingRequest1) {
            Audatex.FraudCheckServiceReferences.pingRequest inValue = new Audatex.FraudCheckServiceReferences.pingRequest();
            inValue.pingRequest1 = pingRequest1;
            Audatex.FraudCheckServiceReferences.pingResponse retVal = ((Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort)(this)).ping(inValue);
            return retVal.pingResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Audatex.FraudCheckServiceReferences.pingResponse> Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort.pingAsync(Audatex.FraudCheckServiceReferences.pingRequest request) {
            return base.Channel.pingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Audatex.FraudCheckServiceReferences.pingResponse> pingAsync(Audatex.FraudCheckServiceReferences.B2BRequest pingRequest1) {
            Audatex.FraudCheckServiceReferences.pingRequest inValue = new Audatex.FraudCheckServiceReferences.pingRequest();
            inValue.pingRequest1 = pingRequest1;
            return ((Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort)(this)).pingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Audatex.FraudCheckServiceReferences.findExternalResponse Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort.findExternal(Audatex.FraudCheckServiceReferences.findExternalRequest request) {
            return base.Channel.findExternal(request);
        }
        
        public Audatex.FraudCheckServiceReferences.B2BResponse findExternal(Audatex.FraudCheckServiceReferences.B2BRequest findExternalRequest1) {
            Audatex.FraudCheckServiceReferences.findExternalRequest inValue = new Audatex.FraudCheckServiceReferences.findExternalRequest();
            inValue.findExternalRequest1 = findExternalRequest1;
            Audatex.FraudCheckServiceReferences.findExternalResponse retVal = ((Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort)(this)).findExternal(inValue);
            return retVal.findExternalResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Audatex.FraudCheckServiceReferences.findExternalResponse> Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort.findExternalAsync(Audatex.FraudCheckServiceReferences.findExternalRequest request) {
            return base.Channel.findExternalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Audatex.FraudCheckServiceReferences.findExternalResponse> findExternalAsync(Audatex.FraudCheckServiceReferences.B2BRequest findExternalRequest1) {
            Audatex.FraudCheckServiceReferences.findExternalRequest inValue = new Audatex.FraudCheckServiceReferences.findExternalRequest();
            inValue.findExternalRequest1 = findExternalRequest1;
            return ((Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort)(this)).findExternalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Audatex.FraudCheckServiceReferences.findInternalResponse Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort.findInternal(Audatex.FraudCheckServiceReferences.findInternalRequest request) {
            return base.Channel.findInternal(request);
        }
        
        public Audatex.FraudCheckServiceReferences.B2BResponse findInternal(Audatex.FraudCheckServiceReferences.B2BRequest findInternalRequest1) {
            Audatex.FraudCheckServiceReferences.findInternalRequest inValue = new Audatex.FraudCheckServiceReferences.findInternalRequest();
            inValue.findInternalRequest1 = findInternalRequest1;
            Audatex.FraudCheckServiceReferences.findInternalResponse retVal = ((Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort)(this)).findInternal(inValue);
            return retVal.findInternalResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Audatex.FraudCheckServiceReferences.findInternalResponse> Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort.findInternalAsync(Audatex.FraudCheckServiceReferences.findInternalRequest request) {
            return base.Channel.findInternalAsync(request);
        }
        
        public System.Threading.Tasks.Task<Audatex.FraudCheckServiceReferences.findInternalResponse> findInternalAsync(Audatex.FraudCheckServiceReferences.B2BRequest findInternalRequest1) {
            Audatex.FraudCheckServiceReferences.findInternalRequest inValue = new Audatex.FraudCheckServiceReferences.findInternalRequest();
            inValue.findInternalRequest1 = findInternalRequest1;
            return ((Audatex.FraudCheckServiceReferences.ClaimsHistoryServicePort)(this)).findInternalAsync(inValue);
        }
    }
}
